spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/runoob?characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
jpa:
  database: MySQL
  show-sql: true
  hibernate:
    naming_strategy:org.hibernate.cfg.ImprovedNamingStrategy