spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/runoob?characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计，"wall"用于防火墙
    filters: stat,wall,log4j
    # 最大活跃数
    maxActive: 20
    # 初始化数量
    initialSize: 1
    # 最大连接等待超时时间
    maxWait: 60000
    # 打开PSCache, 并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectionPropeties属性打开mergeSql功能； 慢sql记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis = 5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

jpa:
  database: MySQL
  show-sql: true
  hibernate:
    naming_strategy:org.hibernate.cfg.ImprovedNamingStrategy